### ISSUE TITLE
Include mission outcome emojis in vote history

### ISSUE THREAD

**Issue by johnbeech** [connected-web/gamebot#25]
From Emma:
>Any chance the vote history could include the mission outcome emojis at the appropriate points?

**Comment by johnbeech** [comment]
Noticed that played actions and mission outcome (beyond the victorious team) are not stored in game state. Added this information so that it can be displayed in vote history at a future time.

See: https://github.com/connected-web/gamebot/commit/3ad940940c674b0af393ce68088c7b9973f844e4

**Comment by johnbeech** [comment]
Fixed in b2397f7

**Comment by EmmaJP** [comment]
Awesome! Forgot I'd asked for this.

**Comment by johnbeech** [comment]
You're welcome :)
