### ISSUE TITLE
Add a command to view team mates

### ISSUE THREAD

**Issue by Leonie-** [connected-web/gamebot#46]
It would be nice if there was a command to remind who your team mates are - maybe something like 'who are my team?". Maybe the teams could be listed when calling 'game state' as well?

**Comment by johnbeech** [comment]
The command `list players` has aliases for `who is playing` and `list teams`. I've added `who are my team` and `who is on my team` to the matcher.

The output of this command now includes team information, for example:
<img width="583" alt="who-is-playing" src="https://user-images.githubusercontent.com/6341696/29362365-981795e4-8283-11e7-9525-c1cd57b26533.png">

I can also add this information to gamestate...

**Comment by hannahbunce** [comment]
Already implemented :)
