### ISSUE TITLE
When a player is eliminated, the turn count is incremented, resulting in the next player's turn being skipped.

### ISSUE THREAD

**Issue by hannahbunce** [connected-web/gamebot#63]

**Comment by johnbeech** [comment]
Attempted fix in https://github.com/connected-web/gamebot/commit/a40e90b0d3f6b291a425041309eee2af9e758d28

Requires play testing on live server with 3 players and a mid game elimination.

**Comment by johnbeech** [comment]
This seems to be fixed... will reopen if we spot any more problems.
