### ISSUE TITLE
Command to start new game with the same teams

### ISSUE THREAD

**Issue by johnbeech** [connected-web/gamebot#95]
Improvement suggestion: “start new game” in codenames as a command. it’s kinda wasteful to have to “reset game” then “start game”.

**Comment by hannahbunce** [comment]
To mimic the 'start new round' functionality in Love Letter.

In Love Letter, it is possible to start a new round/game without having to reset. In Codenames, the functionality is not there.

Might be an idea to re-check the functionality in Resistance as well and perhaps bring all three games' core functions into alignment.

**Comment by johnbeech** [comment]
Created a pull request with desired functionality:
- https://github.com/connected-web/gamebot/pull/96
